#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Vordt
SRCDIRS += ../components/esp32-snippets-master
include $(IDF_PATH)/make/project.mk

