// Auto-generated. Do not edit!

// (in-package control_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let GripperCommand = require('./GripperCommand.js');

//-----------------------------------------------------------

class GripperCommandGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.command = null;
    }
    else {
      if (initObj.hasOwnProperty('command')) {
        this.command = initObj.command
      }
      else {
        this.command = new GripperCommand();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GripperCommandGoal
    // Serialize message field [command]
    bufferOffset = GripperCommand.serialize(obj.command, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GripperCommandGoal
    let len;
    let data = new GripperCommandGoal(null);
    // Deserialize message field [command]
    data.command = GripperCommand.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'control_msgs/GripperCommandGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '86fd82f4ddc48a4cb6856cfa69217e43';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    GripperCommand command
    
    ================================================================================
    MSG: control_msgs/GripperCommand
    float64 position
    float64 max_effort
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GripperCommandGoal(null);
    if (msg.command !== undefined) {
      resolved.command = GripperCommand.Resolve(msg.command)
    }
    else {
      resolved.command = new GripperCommand()
    }

    return resolved;
    }
};

module.exports = GripperCommandGoal;
